client_config_backend: settings
client_config:
 client_id: 556417171119-rr1bust4balcdh117gfep5ung2k9kcpe.apps.googleusercontent.com
 client_secret: w1py0s9N4W-tJnl5mkdqo0OZ

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
 - https://www.googleapis.com/auth/drive.file
 - https://www.googleapis.com/auth/drive.install
